project_directory = './'

include_third_party = true
third_party_color = 'orange'
enable_size = true

include_parents = [
    '/internal'
]

include_children = [
    '/internal'
]

exclude_parents = [
    '/internal/legacy'
]

exclude_children = [
    '/internal/legacy'
]

custom = [
    'user'
]

[colors]
'user' = 'blue'

[extend_ids]
'v\d+$' = 2