project_directory = "./"

include_third_party = false
third_party_color = ""

include_parents = [
    "cli"
]

include_children = [
    "component"
]

exclude_parents = [
    "cli"
]

exclude_children = [
    "component"
]

[colors]
"json" = "green"
"server" = "cyan"