project_directory = './'

include_third_party = true
third_party_color = 'orange'

include_parents = [
    'fs',
    'dot'
]

include_children = [
    'fs',
    'dot'
]

exclude_parents = [
    'fs',
    'dot'
]

exclude_children = [
    'fs',
    'dot'
]

[colors]
'dot' = 'red'

[extend_ids]
'v\d+$' = 2